name: CI for Python Selenium Behave

# Define the triggers for the workflow (push or pull request)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu as the environment

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify Python version

     # Install Chrome and ChromeDriver
      - name: Install Chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: sudo apt-get install -y chromedriver

      # Step 3: Install dependencies (Selenium, Behave, etc.)
      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Install packages from requirements.txt

      # Step 4: Run Behave tests
      - name: Run Behave tests
        run: behave  # Execute the Behave tests
